---
title: "Entre Dev Y Ops"
baseURL: "http://www.entredevyops.es/"

languageCode: "es-es"
defaultContentLanguage: "es"

SectionPagesMenu: "Main"
theme: "edyo"
paginate: 6
uglyurls: true
pygmentsCodeFences: true
pygmentsStyle: "vs"

enableEmoji: true

blackfriday:
  hrefTargetBlank: true

removePathAccents: false
preserveTaxonomyNames: false
taxonomies:
  tags: "tags"

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "rss"

params:
  mainSections: ["posts", "podcasts"]

  Description: "El podcast en el que hablamos sobre desarrollo de aplicaciones, operaciones de sistemas informáticos y todo lo relacionado con la filosofía DevOps"
  Subtitle: "El podcast en el que hablamos sobre desarrollo de aplicaciones, operaciones de sistemas informáticos y todo lo relacionado con la filosofía DevOps"

  cover: "/images/cover.jpg"
  logo: "/images/edyo-logo.png"
  icon: "/images/edyo-icon.png"

  license: "<a target=\"_blank\" href=\"http://creativecommons.org/licenses/by-nc-sa/3.0/deed.es_ES\"><i class=\"fa fa-creative-commons\"></i> BY-NC-SA 3.0</a>"

  cookiesNoticePage: "politica-cookies.html"
  cookiesNoticeMessage: "Esta web utiliza cookies de terceros para mejorar la experiencia de la web y recopilar datos de uso. Si continúas navegando, consideramos que aceptas su uso."

  showToc: false

  googleAnalyticsUserID: "UA-25613214-1"

  disqus: "edyo"
  twitter: "EntreDevYOps"
  LinkedIn: "EntreDevYOps"
  github: "edyo"

  podcast:
    audioBaseUrl: "http://podcast.edyo.es/podcast/"

menu:
  main:
    - Name: "Episodios podcast"
      URL: "/podcasts.html"
      Identifier: "podcasts"
      Weight: 10
    - Name: "Artículos"
      URL: "/posts.html"
      Identifier: "posts"
      Weight: 20
    - Name: "Equipo"
      URL: "/equipo.html"
      Identifier: "team"
      Weight: 30

  subscription:
    - Name: "Podcast RSS"
      URL: "http://feedpress.me/edyo"
      Identifier: "feed-rss-podcasts"
      Pre: "<i class='fa fa-rss'></i>"
      Weight: 10
    - Name: "Podcast en iVoox"
      URL: "https://www.ivoox.com/podcast-entre-dev-y-ops-podcast_sq_f1112910_1.html"
      Identifier: "ivoox"
      Pre: "<i class='fa fa-podcast'></i>"
      Weight: 20
    - Name: "Podcast en iTunes"
      URL: "https://itunes.apple.com/es/podcast/entredevyops-podcast/id866788492"
      Identifier: "itunes"
      Pre: "<i class='fa fa-apple'></i>"
      Weight: 30
    - Name: "Web RSS"
      URL: "/index.xml"
      Identifier: "feed-rss"
      Pre: "<i class='fa fa-rss'></i>"
      Weight: 40
